version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_worker
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - .:/app
    env_file:
      - app/.env
    command: python app/worker.py
