services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # UI
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app123
      RABBITMQ_DEFAULT_VHOST: app_vhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  # (opcional) seu app/worker, caso jรก orquestre aqui
  # app:
  #   build: .
  #   depends_on:
  #     - rabbitmq

volumes:
  rabbitmq_data:
